### ISSUE TITLE
Labels arabic font doesn't support!

### ISSUE THREAD

**Issue by fadiramzi** [apexcharts/react-apexcharts#115]
Hello
I need to make yaxis labels in arabic fonts, but the words appear in reversing way and it looks ugly
is there a solution?

**Comment by junedchhipa** [comment]
Sorry for the delayed response.
Can you please create a codepen demo to demonstrate the issue?

**Comment by ProgFadi** [comment]
Hi,
my data are fetched online with some hard coded and sensitive data like tokens...
for that i attached you a picture about the problem, i think the problem is clear, which is chart label does't arabic text 
![2019-11-14_09-15-16](https://user-images.githubusercontent.com/20383171/70415842-a084bd80-1a6e-11ea-8b4b-3f3b7049fd5f.png)

you library is very nice and good in fact
so in my project i need the arabic supporting please, any advice
regards

**Comment by Bilal-Elmursi** [comment]
use this style `letter-spacing:normal` in CSS file.
 [](https://stackoverflow.com/questions/59245120/apexchart-reactjs-library-doesnt-support-arabic-language-in-the-labels)
