### ISSUE TITLE
react 18 / react-scripts 5

### ISSUE THREAD

**Issue by RokoTechnology** [apexcharts/react-apexcharts#493]
Been using react-apexcharts in our in-house UI library Chart component, building it with rollup, and installing it via npm into our front-end app for about 6 months.

Since I upgraded the frontend app from react 17 + craco to react 18 + react-scripts 5 the chart won't load and I get the following error: 

![image](https://user-images.githubusercontent.com/85127317/222533593-b3e92ca2-9b29-4885-bddb-cd754672b751.png)

I am not 100% sure but this could be related to one of the ReactApexChart props being called "type"?

Would it be possible to add an alias for this prop, something like "chartType"?

**Comment by RokoTechnology** [comment]
I am using the latest versions of apexcharts and react-apexcharts.
The error happens before any data is loaded / passed into the component.

**Comment by cythrawll** [comment]
Ran into this as well trying to get this package to work with remix.

Since the library doesn't support ssr at all, tried using the react document method of using `lazy()` with dynamic `import` to load the library client side. But doing so I keep getting the message in OP's post. 

When I looked at what gets imported from dynamic import I get an object nested twice. so I get { default: { default: ComponentHere }}.

So something is janky about the esm export not being built right I think.

**Comment by rakirox** [comment]
+1

**Comment by RomuDeuxfois** [comment]
Do you have any solution ?
We upgrade our project to ESM and we are facing the same situation.
We need to use the ESM apexcharts instead of commonJS in react-apexcharts import

import ApexCharts from 'apexcharts/dist/apexcharts.common'
