### ISSUE TITLE
Custom tooltip caveat 

### ISSUE THREAD

**Issue by rafalkrupinski** [apexcharts/react-apexcharts#65]
I wanted my custom tooltip made out of a React component, but apexcharts expects a string with HTML code.

Solved it with simple:

```js
import {renderToString} from 'react-dom/server'
const options = {
    tooltip: {
        custom: displayTooltip(model) {
            return renderToString(<CustomComponent/>);
        }
    },
}
```

Regards

**Comment by junedchhipa** [comment]
Unfortunately, the custom tooltip accepts plain HTML string currently.
No workaround as of now.

**Comment by rafalkrupinski** [comment]
So what's wrong with the above code?

**Comment by DevChrisDev** [comment]
@junedchhipa hello, i wonder why my custom tooltip does not follow my border radius style

**Comment by MichaelHindley** [comment]
@DevChrisDev this is because when using renderToString, there are some different behaviours.
An example on how this could be made to work from my codebase is to send the styles down to whatever is being rendered in the renderToString function.

There are other ways you can do this depending on how you are handling theming/styles in your app, YMMW.

Instead of 
```jsx
<Typography variant="h5" color="primary">
  {someString}
</Typography>
```

The above would load the default material-ui theme and override all styles.

Using this approach, you can send the styles down.
```jsx
// in the parent component/outside of renderToString()
const useStyles = makeStyles((theme: Theme) => ({
  h5: {
    ...theme.typography.h3,
    color: theme.palette.primary.light,
  },
}))

...
renderToString(
  <h3 className={classes.h5>
     {someString}
  </h3>
)
```

You could make this simpler in many ways, but this base concept is a quick fix.
